db:
  host: localhost

spring:
  datasource:
    url: jdbc:mysql://${db.host}/fairy_pos
    username: os
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
