spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./data/fairy_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quote_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
